alias exercism_start="docker-compose up -d"
alias exercism_stop="docker-compose stop"
alias exercism_haskell="docker-compose run --rm exercism-haskell"
alias exercism_haskell_test="docker-compose run --rm exercism-haskell"
alias exercism_python="docker-compose run --rm exercism-python"
alias exercism_python_test="docker-compose run --rm exercism-python pytest python/**/*_test.py"
alias exercism_ruby="docker-compose run --rm exercism-ruby"